version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./static/archive:/app/static/archive
    networks:
      - app_network
    # device_requests:
    #   - driver: nvidia
    #     count: all
    #     capabilities: [gpu]

  mongo:
    image: mongo:7.0.5
    ports:
      - "27018:27017"
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  app_network:
